#FROM node:latest
FROM node:lts-bullseye
LABEL maintainer="Akari<masiro.to.akari@gmail.com>"
SHELL ["/bin/bash", "-c"]

##=============================================================
ARG USER_NAME=common
ARG SERVER_PORT=8000
ARG SRC_DIR=../src/node-script

##=============================================================
ENV USER ${USER_NAME}
RUN useradd --create-home --home-dir /home/${USER_NAME} \
    --shell /bin/bash --user-group --groups adm,sudo ${USER_NAME} && \
    echo ${USER_NAME}:${USER_NAME} | chpasswd && \
    echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

##=============================================================
RUN apt update -q
RUN apt install -y vim iputils-ping net-tools dnsutils

##=============================================================
USER ${USER_NAME}
RUN sed -i -e "s/#alias l/alias l/g" /home/${USER_NAME}/.bashrc

##=============================================================
WORKDIR /home/${USER_NAME}/webserver
COPY ${SRC_DIR}/* /home/${USER_NAME}/webserver
#RUN npm install

##=============================================================
EXPOSE ${SERVER_PORT}
#CMD ["node", "server.js", ${SERVER_PORT}]
